### ISSUE TITLE
Any chance include the cam function?

### ISSUE THREAD

**Issue by rayhou0710** [thomaspark-pkj/pyyolo#1]
Thanks for sharing the wrapper code!
I am wondering if by any chance there could be a function of detecting objects using camera.

**Comment by thomaspark-pkj** [comment]
Thank you for your suggestion.
I'm busy now because of the my work. But I'will consider putting the camera function later.
For reference, this is an early version and was created to research object tracking.

**Comment by rayhou0710** [comment]
Thanks!
I am trying to implement that myself by passing an image.data (1D array ) from python to C through module.c but got stuck there. Any chance you know how to do that?
