### ISSUE TITLE
Cuda malloc failed

### ISSUE THREAD

**Issue by hungpt297** [thomaspark-pkj/pyyolo#11]
When running example.py got error:
layer     filters    size              input                output
    0 Cuda malloc failed
: File exists
python: ./darknet/src/utils.c:216: error: Assertion `0' failed.
Aborted (core dumped)

**Comment by thomaspark-pkj** [comment]
I think it is related to darknet. Could you run darknet only without pyyolo?

**Comment by hungpt297** [comment]
Yes, it is problem in darknet, Example run with config
datacfg = 'cfg/voc.data'
cfgfile = 'cfg/yolo.cfg'
weightfile = '../yolo.weights'

Many thanks.
