### ISSUE TITLE
darknet.h: No such file or directory

### ISSUE THREAD

**Issue by RyanCV** [thomaspark-pkj/pyyolo#38]
Hi, I got the following errors when I run "make", any one knows how to solve it?? Thanks.
[pyyolo-master]$ make
```
gcc  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Wno-unused-result -fPIC -I./darknet/src -I./darknet/include -Ofast -DGPU -DCUDNN -c libyolo.c -o obj/libyolo.o
libyolo.c:5:21: fatal error: darknet.h: No such file or directory
 #include "darknet.h"
                     ^
compilation terminated.
make: *** [obj/libyolo.o] Error 1
```

**Comment by rayhou0710** [comment]
@RyanCV  Did you clone the darknet using --recursively ?

**Comment by RyanCV** [comment]
@rayhou0710 I use the command: `git clone --recursive git@github.com:rayhou0710/pyyolo.git` and got the following errors, do you know why?
```
Cloning into 'pyyolo'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by RyanCV** [comment]
@digitalbrain79 I have solved the git problem now. Thanks.

**Comment by luisriera** [comment]
Hi,

I'm having the same issue as RyabCV.  Moreover, I'm not able to use `git clone --recursive git@github.com:rayhou0710/pyyolo.git`.  I get the following error when trying to clone using that command line:
```
`Cloning into 'pyyolo'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
`
Your soon help will be greatly appriciate.

Regards,
Luis

**Comment by luisriera** [comment]
I fix it my issue by using `git clone --recursive https://github.com/digitalbrain79/pyyolo.git`
